- id: commit-issue-prefix
  name: Commit Issue Prefix
  description: Automatically add issue number prefix to commit messages
  entry: commit-issue-prefix
  language: python
  stages: [prepare-commit-msg]
  always_run: true
