- id: add-github-issue-prefix
  name: Add GitHub Issue Prefix
  description: Automatically add GitHub issue number prefix to commit messages
  entry: add-github-issue-prefix
  language: python
  stages: [prepare-commit-msg]
  always_run: true
